### ISSUE TITLE
Tag contrast

### ISSUE THREAD

**Issue by ebullient** [ebullient/obsidian-theme-ebullientworks#10]
The tags for me (using a light version) are too dark to read. I've tried to find where I can change them, but as of today I haven't found it.  Currently, it is a reddish color on black.  I need more contrast. The hover is black on black. 

I appreciate the help!

_Originally posted by @KzBeck in https://github.com/ebullient/obsidian-theme-ebullientworks/discussions/7#discussioncomment-1905942_

**Comment by ebullient** [comment]
https://github.com/ebullient/obsidian-theme-ebullientworks/discussions/7#discussioncomment-1907177

**Comment by KzBeck** [comment]
Okay, Yes, I suspect it may be from **Colored Folders** or maybe **Combine Nested tag colors and Highlight colors**. I will try to resolve it. Thanks for your time and pointing me in a direction.  

Love the theme!
