### ISSUE TITLE
Change H1 to Title Case vs Upper Case

### ISSUE THREAD

**Issue by KzBeck** [ebullient/obsidian-theme-ebullientworks#12]
I have tried to change the h1 to a standard title case like **Chapter 12 Mobile**.  I tried the text-transform, but that did not work.  I turned off all Snippets in case, but that did to work either.  I found one reference to text-transform but changing it did not resolve the issue.

I find this font style hard to read. I would appreciate your assistance in pointing me in the right direction.

I appreciate any help you can provide.

**Comment by ebullient** [comment]
Try this in a snippet: 

```
.workspace .cm-header-1,
.workspace h1,
.print .cm-header-1,
.print h1 {
  font-variant: common-ligatures normal;
}
```

**Comment by KzBeck** [comment]
Thank you .
font-variant: none; worked
