### ISSUE TITLE
the H1 title word height is low

### ISSUE THREAD

**Issue by shuivin** [ebullient/obsidian-theme-ebullientworks#13]
+ when i input the word with **lowercase**, the H1 height is low.
+ while i input the word with **uppercase**, the H1 height is normal.
<img width="833" alt="image" src="https://user-images.githubusercontent.com/1046701/162448818-8043334c-a735-4ed0-8df9-0e5796212190.png">

**Comment by ebullient** [comment]
it is styled with small caps... (making the lowercase letters small capital letters). So this is expected.

Write as "Head test in sentence case" or "Head Test in Title Case" and you'll see what I mean.

**Comment by shuivin** [comment]
Thanks, i got it. Yes, it is expected feature./cry
**Is there any css method  to use normal caps in Title Case?**  I just close this feature by css.
```css
.print h1 {
  font-variant: none;
  border-bottom: 1px dotted #F00;
}```

**Comment by ebullient** [comment]
I can add it to style settings. ;)

**Comment by shuivin** [comment]
i has try all the header style blew, found the small-caps is the best style, finally. /cry
https://developer.mozilla.org/zh-CN/docs/Web/CSS/font-variant-caps

**Comment by ebullient** [comment]
[69be6a6](https://github.com/ebullient/obsidian-theme-ebullientworks/commit/69be6a668cb3f4d631986bb7e4ddeffe7f1c2b23)

There is a new style setting for you to toggle the font-variant for the headers. ;)

**Comment by shuivin** [comment]
nice work!
