### ISSUE TITLE
[FR] Add default Icons to Reference and TOC

### ISSUE THREAD

**Issue by sigrunixia** [ebullient/obsidian-theme-ebullientworks#21]
Hello There! It's very quiet here. 

I normally do not use admonitions anymore, as I am head-deep in custom callout land, but I have always enjoyed your interpretation of reference and too and so use those. Why reinvent a perfectly good wheel? 

However, the one thing lacking is the icons missing on them. I noticed in the scss files that the css for both of them is standard, which means it's something I can possibly assist with! 💃🏻 I'll be happy to submit a PR with a simple update, or you can stick the 2 lines of code in there, your choice. 

Now, the hard part. Icon choices. The current recommended ones are font-awesome icons. Unless you want to embed those or a user has them already installed, thats a no-go. So here are some Lucide that I think may work. 

Reference: 

1. library
2. album
3. pin (This is a left fielder, for fun).

ToC:

1. layout-list
2. clipboard-list

What do you think?

**Comment by ebullient** [comment]
PR away! I still use the admonition plugin, and have had the icon set that way for so long.. ;)
but I'm happy for a PR!

For the reference type, I use a book. Any of the others (even the fun one), seem great.

I think I like layout-list or just list better than the clipboard list for a ToC..

**Comment by sigrunixia** [comment]
Sadly the book icon for lucide is lackluster compared to the font-awesome one. ![book](https://user-images.githubusercontent.com/68425372/211674131-e2e21af6-950e-4943-bd32-ad2289a2bc12.png). So plain :( I think library seems closest in feel, since its citation style. 

List is used for the example callout by default, so layout-list it is!
