### ISSUE TITLE
Dark theme PDF exporting issue

### ISSUE THREAD

**Issue by emisjerry** [ebullient/obsidian-theme-ebullientworks#3]
There'are some problem while exporting to PDF in dark theme.

![image](https://user-images.githubusercontent.com/131511/142143134-e0e0bf90-3ab1-46f8-b55f-8942e40842fc.png)

**Comment by ebullient** [comment]
Does switching to light mode work better (minimally as a workaround)?

**Comment by emisjerry** [comment]
light theme is ok.

**Comment by ebullient** [comment]
Will work through this in stages. ;) Thanks for opening the issue.
