### ISSUE TITLE
[Bug]: Style Settings Headers Error

### ISSUE THREAD

**Issue by sigrunixia** [ebullient/obsidian-theme-ebullientworks#41]
When editing the style setting "Heading Font Caps Variant", Stylesettings begins erroring out.

I honestly do not use headers enough to determine if it is hindering the functionality of the setting; it does not seem to hinder color settings. I have included a gif of the action and error.

![heading-stylesettings](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/68425372/7f197961-f16d-4417-b4ec-c62d95fbf8a0)

Looking at the style settings snippet, I do not see anything outwardly incorrect, but there might be something I am missing.

**Comment by ebullient** [comment]
I can't recreate this. What are all of the versions? Do you have a partial/alpha/experimental build of anything? The values you're picking are all valid css values..

**Comment by sigrunixia** [comment]
I have determined this was likely an issue with the older data.json I had with Stylesettings, so no issue! Closing. :)
