### ISSUE TITLE
Block embeds cleanly / flush 

### ISSUE THREAD

**Issue by SemanticBeeng** [ebullient/obsidian-theme-ebullientworks#57]
For ``[[embed links#^blockid]]`` and `[[embed links#heading]]` can the theme remove all clutter ?

![image](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/9296536/9e2a7ad3-05bd-447b-9fce-bf958282f769)

should look closer to 
![image](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/9296536/dd6baebc-7737-42bd-85f9-f57d3a20fbff)

**Comment by ebullient** [comment]
Can you share the source you're using for that image, please?
And also be clear which style settings you're using, and if you have any cssClass values set (and if so, what those snippets contain)?

**Comment by SemanticBeeng** [comment]
```
* ![[cosigner#^def|alt=seamless]]
* ![[First Cosigner#^def|alt=seamless]]
* ![[Quorum Cosigner#^def|alt=seamless]]
* ![[Final Cosigner#^def|alt=seamless]]
```

**Comment by SemanticBeeng** [comment]
Noticed that when embed text is shorter than one line the embed renders "seamless", a desired

![image](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/9296536/10c93374-2e03-4f06-99ed-5b1f09a67d65)

**Comment by SemanticBeeng** [comment]
I figured it; all complex block embeds look clean and flush now

![image](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/9296536/b809270d-8ad0-4dec-bb15-2b44f0a203aa)

Using `AnuPpucin` theme.
All of the use these two a `![[device-locked key#^def|^ wtall]]`

Changed above to top alignment from middle.

```
/* Code kindly provided by @zamsyt#4459 on discord */

:is(li, .HyperMD-list-line) > .internal-embed[alt*='^'] {
  display: inline-block;
  vertical-align: top; /**from middle;*//
}
```
And this style makes the block div smaller so it can slide in place (assuming).
https://github.com/SlRvb/Obsidian--ITS-Theme/blob/58900e2ed13b2a2f65a8dee5118fc64421f53fc7/Snippets/S%20-%20Embed%20Adjustments.css#L43-L45

These two extra css sheets are active

![image](https://github.com/ebullient/obsidian-theme-ebullientworks/assets/9296536/ac2f1663-cdc5-44d7-a402-dde061d228d7)

Rough explanation.

**Comment by ebullient** [comment]
Ok. So I've lost track of what you're asking for here. 

- Are you asking for support for block reference based styles (wtall, etc)? If that snippet works well with my theme, I think that's a great answer. I think it is safest to allow the ITS theme maintainer to keep evolving those snippets. 

- If you're asking for general cleanup of embedded block references inside list items, then I can do that.

**Comment by SemanticBeeng** [comment]
> Are you looking at live preview? 

Looking to render and publish in a way that is consistently rendering clean embeds.

> And are you planning on using other snippets that provide embed adjustments?

Hmm ... ideally no, would like the embed adjustments to be common, not theme specific.
Now I have to use a few things together to make it work but it is not desireable.

Not sure I understood the questions fully.

**Comment by ebullient** [comment]
Ok. you opened this issue specifically with _a_ theme. 

I don't currently have plans to support `|alt=seamless` tags, as those are not a default part of Obsidian. ITS (for example) provides a standalone snippet that brings in that function, which should work with other themes.

**Comment by SemanticBeeng** [comment]
Thanks for everything!
