### ISSUE TITLE
Selected text highlighting is not visible in Light mode

### ISSUE THREAD

**Issue by mpalian** [ebullient/obsidian-theme-ebullientworks#76]
When I select some text, I cannot see the selection, it is either so low in contrast or the same colour as the background. In dark mode, it is a bit discrete, but certainly visible.

**Comment by ebullient** [comment]
have you checked for theme updates?
using default primary/secondary? or custom?
mobile or desktop? 
screenshot for what you see would be excellent.

**Comment by mpalian** [comment]
> have you checked for theme updates? using default primary/secondary? or custom? mobile or desktop? screenshot for what you see would be excellent.

Yes, I have the latest theme. It is the default background, I have not fiddled with CSS. Happening on macOS desktop.

Here are the dark mode and light mode examples with "Math and Statistics" text selected. Clear in dark mode, invisible in light mode.

<img width="329" alt="Screenshot 2023-12-11 at 18 06 16" src="https://github.com/ebullient/obsidian-theme-ebullientworks/assets/67279897/7c2ac130-966e-4bfa-ad14-766e48ef76b5">

<img width="270" alt="Screenshot 2023-12-11 at 18 07 28" src="https://github.com/ebullient/obsidian-theme-ebullientworks/assets/67279897/a649e915-4058-4bcb-82b3-9ef6a5172143">

**Comment by ebullient** [comment]
Mine looks like this (also defaults):
<img width="657" alt="image" src="https://github.com/ebullient/obsidian-theme-ebullientworks/assets/808713/48f8d98c-9b42-41b9-861f-930edf165f73">

If you use the folder button to navigate to the theme: 
<img width="137" alt="image" src="https://github.com/ebullient/obsidian-theme-ebullientworks/assets/808713/e1169485-3e84-4d8f-a61b-b7b1e48532e7">

Can you confirm the version (manifest.json) is 0.7.19? Should be, but both of those colors look like settings I fixed awhile ago.

**Comment by ebullient** [comment]
Any snippets?

**Comment by sigrunixia** [comment]
@mpalian Can you provide your "Show Debug Info"?

In Obsidian, use the command "Show debug info," then copy it and share it here.

**Comment by mpalian** [comment]
> Any snippets?

None.

**Comment by mpalian** [comment]
> @mpalian Can you provide your "Show Debug Info"?

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 23.1.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Ebullientworks v0.7.19
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 1
		1: Importer v1.5.5

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by ebullient** [comment]
I know why. ;) Do you have the style settings plugin, by chance?

**Comment by ebullient** [comment]
New release will be out shortly.. give that a try. ;)

**Comment by mpalian** [comment]
I only have the importer and sliding panels plugins. I'll be waiting for the new release, thnx.

Is there a snippet it would be worthwhile trying?

**Comment by ebullient** [comment]
nope. It was a missing default setting that I didn't notice because I always have the style settings plugin around. The sandbox repo helped me spot it. You should be all set. Thanks for reporting the issue!

**Comment by mpalian** [comment]
Many thanks ... this update solved the problem (as you knew it would).

**Comment by ebullient** [comment]
Thank you for confirming. ;)
